version: "3.4"

services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=redreamer
    ports:
      - 5432:5432

  api:
    image: api:latest
    ports:
      - 8080:8080
    environment:
      - ENV=local
      - PORT=8080
      - DEBUG=true
    depends_on:
      - postgres
