basePath: /api
host: localhost:8080
info:
  contact:
    email: kai.chihkaiyu@gmail.com
    name: Chih Kai Yu
  description: Task Todo API server
  title: Task Todo API
  version: 0.0.1
paths: {}
swagger: "2.0"
