
-- +migrate Up
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS tasks (
    pk SERIAL PRIMARY KEY NOT NULL,
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
	name VARCHAR(50) NOT NULL DEFAULT '',
	status SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT NULL
);

CREATE UNIQUE INDEX tasks_id_idx ON tasks (id);

-- +migrate Down
DROP TABLE IF EXISTS tasks;
